### ISSUE TITLE
Unable to install on Manjaro Linux

### ISSUE THREAD

**Issue by jc00ke** [andreypopp/esy-solve-cudf#10]
I have `node` installed globally, so seems like I should also have/want `esy` installed globally as well. Maybe that's not correct? (I'm not fluent in the js/node ecosystem :wink: )

```
> sudo npm install -g esy                                                       
/usr/bin/esy -> /usr/lib/node_modules/esy/_build/default/esy/bin/esyCommand.exe

> esy-solve-cudf@0.1.10 postinstall /usr/lib/node_modules/esy/node_modules/esy-solve-cudf
> node ./postinstall.js

fs.js:122
    throw err;
    ^

Error: EACCES: permission denied, rename '/usr/lib/node_modules/esy/node_modules/esy-solve-cudf/platform-linux/esySolveCudfCommand.exe' -> '/usr/lib/node_modules/esy/node_modules/esy-solve-cudf/esySolveCudfCommand.exe'
    at Object.renameSync (fs.js:617:3)
    at install (/usr/lib/node_modules/esy/node_modules/esy-solve-cudf/postinstall.js:10:6)
    at Object.<anonymous> (/usr/lib/node_modules/esy/node_modules/esy-solve-cudf/postinstall.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esy-solve-cudf@0.1.10 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esy-solve-cudf@0.1.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-20T18_26_29_084Z-debug.log
```

First saw this when trying to install `esy` to play around with [revery](https://github.com/bryphe/revery).

**Comment by andreypopp** [comment]
@jc00ke pass `--unsafe-perm=true` if you are using npm with sudo:
```
% sudo npm install -g esy --unsafe-perm=true
```

**Comment by jc00ke** [comment]
Thanks! I need to set up node/npm again using a local install. Someday.
