### ISSUE TITLE
Failure installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by bluddy** [andreypopp/esy-solve-cudf#11]
I'm getting an error at a rename/move. This error was discovered in a docker container, but it happens on my actual ubuntu 16.04 machine as well.

```
opam@f8301a086464:~/esy_test$ sudo npm install -g esy-solve-cudf
/usr/local/bin/esy-solve-cudf -> /usr/local/lib/node_modules/esy-solve-cudf/esySolveCudfCommand.exe

> esy-solve-cudf@0.1.10 postinstall /usr/local/lib/node_modules/esy-solve-cudf
> node ./postinstall.js

fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/esy-solve-cudf/platform-linux/esySolveCudfCommand.exe' -> '/usr/local/lib/node_modules/esy-solve-cudf/esySolve
CudfCommand.exe'
    at Object.renameSync (fs.js:598:3)
    at install (/usr/local/lib/node_modules/esy-solve-cudf/postinstall.js:10:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/esy-solve-cudf/postinstall.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esy-solve-cudf@0.1.10 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esy-solve-cudf@0.1.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-09T16_49_06_533Z-debug.log
```

**Comment by bluddy** [comment]
Looks like I was just missing --unsafe-perm. Closing.
